[project]
name = "shared"
version = "0.1.0"
description = "shared items for monkeycar project"
readme = "README.md"
authors = [
    { name = "masaru ogawa", email = "masaruo@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.14.11",
]
