[project]
name = "pc-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "shared",
    "keras>=3.13.0",
    "matplotlib>=3.10.8",
    "numpy<2.0.0",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.3",
    "pillow>=12.1.0",
    "scikit-learn>=1.8.0",
    "tensorflow>=2.15.0",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
shared = { path = "../shared", editable = true }

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.11",
]

[tool.ruff]
exclude = [
    "tests/*",
    "sample/*",
]

[tool.mypy]
exclude = [
    "tests/",
    "sample/",
]
