[project]
name = "cnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "masaru ogawa", email = "masaruo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.1",
    "pydantic>=2.12.5",
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.14.14",
]
