[project]
name = "cnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "masaru ogawa", email = "masaruo@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pydantic",
]


[dependency-groups]
dev = [
    "mypy",
    "pytest>=9.0.2",
    "ruff",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Hatchlingはデフォルトで "src/<パッケージ名>" を探してくれますが
# 明示的に指定したい場合は以下を書きます（通常は自動検出されます）
[tool.hatch.build.targets.wheel]
packages = ["src/cnn"]
